- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  aliases:
      ec7e821ca4c81eed057f0b0ca66f895641e96018: 'Echo'
      bcade7d1ebb21a0562fb646e2040db6deac8736c: 'Bose'
      ee941b2cd437d4b41afd94bf5055d043: 'TV_sovrummet'
      ce4ad588b2bb66a32b0481f17c6a6097: 'Google cast'
