- platform: mqtt
  name: "Holiday Lights"
  command_topic: "bruh/mqttstrip/setpower"
  state_topic: "bruh/mqttstrip/setpowerpub"
  rgb_state_topic: "bruh/mqttstrip/setcolorpub"
  rgb_command_topic: "bruh/mqttstrip/setcolor"
  brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
  brightness_command_topic: "bruh/mqttstrip/setbrightness"
  optimistic: false

- platform: mqtt
  name: "Holiday Lights Outside2"
  command_topic: "bruh3/outside/setpower"
  state_topic: "bruh3/outside/setpowerpub"
  rgb_state_topic: "bruh3/outside/setcolorpub"
  rgb_command_topic: "bruh3/outside/setcolor"
  brightness_state_topic: "bruh3/outside/setbrightnesspub"
  brightness_command_topic: "bruh3/outside/setbrightness"
  optimistic: false
