- platform: mqtt
  name: "Holiday Lights Outside1"
  command_topic: "bruh1/outside/setpower"
  state_topic: "bruh1/outside/setpowerpub"
  rgb_state_topic: "bruh1/outside/setcolorpub"
  rgb_command_topic: "bruh1/outside/setcolor"
  brightness_state_topic: "bruh1/outside/setbrightnesspub"
  brightness_command_topic: "bruh1/outside/setbrightness"
  optimistic: false

- platform: mqtt
  name: "Holiday Lights Outside2"
  command_topic: "bruh3/outside/setpower"
  state_topic: "bruh3/outside/setpowerpub"
  rgb_state_topic: "bruh3/outside/setcolorpub"
  rgb_command_topic: "bruh3/outside/setcolor"
  brightness_state_topic: "bruh3/outside/setbrightnesspub"
  brightness_command_topic: "bruh3/outside/setbrightness"
  optimistic: false
