#home
homeassistant:
  name: Home
  latitude: !secret lat 
  longitude: !secret lon 
  elevation: 50
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customizations/
  #auth_providers:
  #- type: legacy_api_password
  #  api_password: !secret api_password

#startup standard things
frontend:
  themes: !include_dir_merge_named themes/

config:
hassio:
history:
logbook:
system_health:
hacs:
  token: !secret git_custom_updater_token

http: 
  base_url: !secret base_url_hidden

influxdb:
  host: !secret influxdbhost
  port: !secret influxport
  database: homeassistant
  username: !secret influxuser
  password: !secret influxpsw
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id1

#lovelace yaml conf enabled
lovelace:
  mode: yaml

#all includes
weather: !include_dir_merge_list components/weather/
media_player: !include_dir_merge_list components/mediaplayers/
panel_iframe: !include_dir_merge_named panels/
camera: !include_dir_merge_list components/cameras/
light: !include_dir_merge_list components/lights/
alarm_control_panel: !include components/alarm_system/alarm_control_panel.yaml
sensor: !include_dir_merge_list components/sensors/
binary_sensor: !include_dir_merge_list components/binary_sensors/
group: !include_dir_merge_named components/groups/
input_select: !include components/input_selects/holiday_lights.yaml
input_number: !include components/input_numbers/holiday_lights.yaml
device_tracker: !include components/device_tracker/device_tracking.yaml
recorder: !include components/recorders/recorders.yaml
input_boolean: !include_dir_merge_named components/input_boolean/
switch: !include_dir_merge_list components/switches/
automation: !include_dir_merge_list automations/
timer: !include_dir_merge_named components/timers/
alexa_media: !include_dir_merge_named components/alexa_media/
person: !include_dir_merge_list persons/
notify: !include components/notify/telegram.yaml

# to do, still old structure
script: !include scripts.yaml

tts:
  - platform: google_cloud
    key_file: google_cloud.json
    language: en-US
    gender: male
    voice: en-US-Wavenet-F
    encoding: linear16
    speed: 0.9
    pitch: -2.5
    gain: 5.0


