homeassistant:
  name: Home
  latitude: !secret lat 
  longitude: !secret lon 
  elevation: 50
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customizations/
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 192.168.10.0/24
frontend:
  themes: !include_dir_merge_named themes/
stream:
cloud:
cast:
sun:
mobile_app:

config:
hassio:
history:
ffmpeg:
logbook:
system_health:

http: 
  base_url: !secret base_url_hidden

influxdb:
  host: !secret influxdbhost
  port: !secret influxport
  database: homeassistant
  username: !secret influxuser
  password: !secret influxpsw
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id1

lovelace:
  mode: yaml

  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: generated.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false
    lovelace-ui: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui-lovelace.yaml
      title: Standard
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false

weather: !include_dir_merge_list components/weather/
media_player: !include_dir_merge_list components/mediaplayers/
camera: !include_dir_merge_list components/cameras/
light: !include_dir_merge_list components/lights/
alarm_control_panel: !include components/alarm_system/alarm_control_panel.yaml
sensor: !include_dir_merge_list components/sensors/
binary_sensor: !include_dir_merge_list components/binary_sensors/
group: !include_dir_merge_named components/groups/
input_select: !include_dir_merge_named components/input_selects/
input_number: !include components/input_numbers/holiday_lights.yaml
device_tracker: !include components/device_tracker/device_tracking.yaml
recorder: !include components/recorders/recorders.yaml
input_boolean: !include_dir_merge_named components/input_boolean/
switch: !include_dir_merge_list components/switches/
automation: !include_dir_merge_list automations/
timer: !include_dir_merge_named components/timers/
person: !include_dir_merge_list persons/
notify: !include components/notify/telegram.yaml

# to do, still old structure
script: !include scripts.yaml

tts:
  - platform: google_cloud
    key_file: google_cloud.json
    language: en-US
    gender: male
    voice: en-US-Wavenet-F
    encoding: mp3
    speed: 0.9
    pitch: -2.5
    gain: +5.0

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 14200

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

