title: Home Control Panel
resources: !include_dir_list lovelace/resources
custom_header:
  compact_mode: true
  header_text: '{{ deviceID }}'

  exceptions:
    - conditions:
        device_id: 
          - 93fcf001-4ff8e106
          - cfe8cda0-d0379e91
      config:
        kiosk_mode: true

views:
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/monitor.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/sensors.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/trafiken.yaml
  - !include lovelace/views/auto.yaml
  - !include lovelace/views/holidaylight.yaml
  - !include lovelace/views/outside_beer.yaml
  - !include lovelace/views/blixt.yaml


