title: Home Control Panel
resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/sensors.yaml
  - !include lovelace/views/monitor.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/grafana.yaml
  - !include lovelace/views/trafiken.yaml
  - !include lovelace/views/simple.yaml
  - !include lovelace/views/tabletview.yaml
  - !include lovelace/views/auto.yaml
  - !include lovelace/views/octoprint.yaml
  #- !include lovelace/views/kris.yaml
  #- !include lovelace/views/light_rgb_makeup.yaml
  - !include lovelace/views/holidaylight.yaml
  - !include lovelace/views/cam2.yaml
  - !include lovelace/views/stream.yaml

cch:
  menu: show
  notifications: clock
  voice: hide
  options: show
  clock_format: 24
  clock_am_pm: false
  clock_date: false
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
        media_query: "(max-width: 600px)"
        notifications: overflow
        voice: overflow
        menu: overflow
        swipe: true