- platform: generic
  name: Streaming1
  still_image_url: http://192.168.10.57/jpg/image.jpg
  stream_source: rtsp://192.168.10.57:554
  verify_ssl: false
  username: admin
  password: 12345678
- platform: generic
  name: Streaming2
  still_image_url: http://192.168.10.57/jpg/image.jpg
  stream_source: rtsp://192.168.10.57:554
  verify_ssl: false
  username: admin
  password: admin