- platform: manual_mqtt
  state_topic: home/alarm
  command_topic: home/alarm/set
  pending_time: 5
  delay_time: 0
  trigger_time: 300
  code: !secret alarmpin
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
  triggered:
    pending_time: 0