- alias: "brandlarm1"
  id: '33334443434235467684345345785245'
  trigger:
    platform: mqtt
    topic: esp/433
    # Optional
    payload: '7256488'
  action: 
    - service: mqtt.publish
      data:
        topic: "home/ESP_LED_BEDROOM/set"
        payload: '{"state": "ON", "effect": "flash"}'
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id: light.esp_led_bedroom

