- alias: bedroom_small_light_morning_weekdays
  id: '65656656565658878788787878'
  trigger:
  - platform: time
    at: '06:15:00'
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp
  - delay: '01:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp

- alias: bedroom_small_light_morning_weekends
  id: '6565665768523427654878'
  trigger:
  - platform: time
    at: '08:15:00'
  condition: 
  - condition: time
    weekday:
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp
  - delay: '01:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp

- alias: bedroom_small_light_evening_on
  id: '6562222222222222444422222222223'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  condition: 
  - condition: time
    before: '20:00:00' 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp

- alias: bedroom_small_light_evening_off
  id: '6562333434322342322222223'
  trigger:
  - platform: sun
    event: sunset
    offset: '+04:00:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - input_boolean.bedroom_small_lamp