- alias: closet_aquariums_on
  id: '65222221111322323234565461228'
  trigger:
  - platform: time
    at: '11:03:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - input_boolean.akvarium_odling

- alias: closet_aquariums_off
  id: '652222211111228'
  trigger:
  - platform: time
    at: '23:03:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - input_boolean.akvarium_odling