- alias: holiday_lights_evening_solid
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "05:59:00"
  action:
    service: input_select.select_option
    entity_id: input_select.holiday_led_effect
    data_template:
      option: >
        {% if now().strftime("%m%d")|int == 0101 %}
          Solid
        {% else %}
          Solid
        {% endif %}
  id: 1fe49fca51ad499f81csdfsf98711254f2a33


