
- alias: "Animation_Speed_Outside"
  id: '312124533343421245888787651212534'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_number.lab_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "bruh1/outside/setanimationspeed"
        payload: '{{ trigger.to_state.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: "bruh3/outside/setanimationspeed"
        payload: '{{ trigger.to_state.state | int }}'
