        
- alias: "Holiday Input Effect Outside"
  id: '3121245333434212453466611212534'
  initial_state: True
  
  trigger:
    - platform: state
      entity_id: input_select.holiday_led_effect
    #  entity_id: input_select.holiday_led_effect_outside
  action:
    - service: mqtt.publish
      data_template:
        topic: "bruh1/outside/seteffect"
        payload: '{{ trigger.to_state.state | string }}'
    - service: mqtt.publish
      data_template:
        topic: "bruh3/outside/seteffect"
        payload: '{{ trigger.to_state.state | string }}'

