- alias: kitchen_odling_on
  id: '6522225434534521111322323231228'
  trigger:
  - platform: time
    at: '09:03:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - input_boolean.kitchen_odling

- alias: kitchen_odling_off
  id: '65222221342341111228'
  trigger:
  - platform: time
    at: '21:03:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - input_boolean.kitchen_odling