- alias: bedroom_small_light_morning_weekdays
  id: '651111118788787878'
  trigger:
  - platform: time
    at: '06:15:00'
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.sonoff_basic_relay
  - delay: '01:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.sonoff_basic_relay

- alias: bedroom_small_light_morning_weekends
  id: '656562222222254878'
  trigger:
  - platform: time
    at: '08:15:00'
  condition: 
  - condition: time
    weekday:
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.sonoff_basic_relay
  - delay: '01:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.sonoff_basic_relay

- alias: bedroom_small_light_evening_on
  id: '656255522224344112212222222223'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  condition: 
  - condition: time
    before: '20:00:00' 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.sonoff_basic_relay

- alias: bedroom_small_light_evening_off
  id: '656233343432665234673422223'
  trigger:
  - platform: sun
    event: sunset
    offset: '+07:00:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.sonoff_basic_relay