- alias: livingroom_small_back_lamps_evening_on
  id: '652222211111228'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.wallsocket_2_relay

- alias: livingroom_small_back_lamps_evening_off
  id: '333322211112232312'
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:01:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wallsocket_2_relay
