- alias: livingroom_small_back_lamps_morning_weekdays
  id: '65222221231111228'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.wallsocket_3_relay

- alias: livingroom_small_back_lamps_evening_off
  id: '64444332333322567635432'
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:01:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wallsocket_3_relay