- alias: livingroom_small_light_morning_weekdays
  id: '651111118788787878'
  trigger:
  - platform: sun
    event: sunrise
    offset: "-00:30:00"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.wall_five_two_l2

- alias: livingroom_small_light_morning_off
  id: '6562333434326651312315234673422223'
  trigger:
  - platform: sun
    event: sunrise
    offset: '+02:14:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wall_five_two_l2


- alias: livingroom_small_light_evening_on
  id: '656255522224344112212222222223'
  trigger:
  - platform: sun
    event: sunset
    offset: '-03:00:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.wall_five_two_l2

- alias: livingroom_small_light_evening_off
  id: '656233343432665234673422223'
  trigger:
  - platform: sun
    event: sunset
    offset: '+04:00:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wall_five_two_l2