- alias: livingroom_front_ceiling_on_when_dark
  id: '651111118788787878'
  trigger:
    platform: state
    entity_id: input_boolean.light_sensor_outside
    to: 'on'
  condition: 
  - condition: time
    after: '08:00:00'
    before: '22:30:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.wall_five_two_l2

- alias: livingroom_front_ceiling_off_when_light
  id: '6511113252546547567856894'
  trigger:
    platform: state
    entity_id: input_boolean.light_sensor_outside
    to: 'off'
  condition: 
  - condition: time
    after: '08:00:00'
    before: '22:30:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wall_five_two_l2

- alias: livingroom_front_ceiling_off_night
  id: '6511113252324243242342424'
  trigger:
    platform: time
    at: "22:30:10"
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.wall_five_two_l2