- alias: livingroom_kitchen_morning_weekdays
  id: '578784565434565463546576'
  trigger:
    platform: sun
    event: sunrise
    offset: "-01:00:00"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.kitchen1
  - delay: '04:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.kitchen1

- alias: livingroom_kitchen_morning_weekends
  id: '345345345343453455367868'
  trigger:
    platform: sun
    event: sunrise
    offset: "-01:30:00"
  condition: 
  - condition: time
    weekday:
      - sat
      - sun 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.kitchen1
  - delay: '04:00:00'
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.kitchen1

- alias: livingroom_kitchen_evening_on
  id: '1231235433453455453453453'
  trigger:
  - platform: sun
    event: sunset
    offset: '-01:32:00'
  condition: 
  - condition: time
    before: '22:00:00' 
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - switch.kitchen1

- alias: livingroom_kitchen_evening_off
  id: '64444333332223423426567635432'
  trigger:
  - platform: sun
    event: sunset
    offset: '+07:02:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.kitchen1