- alias: "Makeup Input Effect"
  id: '312124530656741212534'
  initial_state: True
  
  trigger:
    - platform: state
      entity_id: input_select.makeup_led_effect
  action:
    - service: mqtt.publish
      data_template:
        topic: "bruh2/makeup/seteffect"
        payload: '{{ trigger.to_state.state | string }}'
        