
- platform: template
  sensors:
    outsidefarm1_soil_conv:
      friendly_name: "Testar"
      unit_of_measurement: 'soil'
      value_template: "{{ states('sensor.outsidefarm1_soil')|float * 1024 }}"

- platform: template
  sensors:
    outsidefarm2_soil_conv:
      friendly_name: "Testar2"
      unit_of_measurement: 'soil'
      value_template: "{{ states('sensor.outsidefarm2_soil')|float * 1024 }}"