
- platform: mqtt
  name: "livingroom_ir_esp_temp"
  state_topic: "esp/IR/temp"
  unit_of_measurement: 'c'

- platform: mqtt
  name: "livingroom_ir_esp_humid"
  state_topic: "esp/IR/humid"
  unit_of_measurement: '%'